import { Product } from "./types";
import P1 from "/public/p1.png";
import P2 from "/public/p2.png";
import P3 from "/public/p3.png";
import P4 from "/public/p4.bmp";
import P5 from "/public/p5.bmp";
import P6 from "/public/p6.bmp";
import P7 from "/public/p7.bmp";
import P8 from "/public/p8.bmp";
import P9 from "/public/p9.bmp";
import P10 from "/public/p10.bmp";
import P11 from "/public/p11.bmp";

export const products: Product[] = [
  {
    id: 1,
    name: "Product 1",
    tagline: "Dress",
    category: "female",
    price: 200,
    image: P1,
    discount: 2,
    qty: 1,
    slug: "p1",
  },
  {
    id: 2,
    name: "Product 2",
    tagline: "Dress",
    category: "female",
    price: 600,
    image: P2,
    discount: 2,
    qty: 1,
    slug: "p2",
  },
  {
    id: 3,
    name: "Product 3",
    tagline: "Dress",
    category: "female",
    price: 900,
    image: P3,
    discount: 2,
    qty: 1,
    slug: "p3",
  },
  {
    id: 4,
    name: "Product 4",
    tagline: "Dress",
    category: "female",
    price: 200,
    image: P4,
    discount: 2,
    qty: 1,
    slug: "p4",
  },
  {
    id: 5,
    name: "Product 5",
    tagline: "Dress",
    category: "female",
    price: 200,
    image: P5,
    discount: 2,
    qty: 1,
    slug: "p5",
  },
  {
    id: 6,
    name: "Product 6",
    tagline: "Dress",
    category: "female",
    price: 200,
    image: P6,
    discount: 2,
    qty: 1,
    slug: "p6",
  },
  {
    id: 7,
    name: "Product 7",
    tagline: "Dress",
    category: "female",
    price: 890,
    image: P7,
    discount: 2,
    qty: 1,
    slug: "p7",
  },
  {
    id: 8,
    name: "Product 8",
    tagline: "Dress",
    category: "female",
    price: 1200,
    image: P8,
    discount: 2,
    qty: 1,
    slug: "p8",
  },
  {
    id: 9,
    name: "Product 9",
    tagline: "Dress",
    category: "female",
    price: 1200,
    image: P9,
    discount: 2,
    qty: 1,
    slug: "p9",
  },
  {
    id: 10,
    name: "Product 10",
    tagline: "Dress",
    category: "male",
    price: 1200,
    image: P10,
    discount: 2,
    qty: 1,
    slug: "p10",
  },
  {
    id: 11,
    name: "Product 11",
    tagline: "Dress",
    category: "male",
    price: 1200,
    image: P11,
    discount: 2,
    qty: 1,
    slug: "p11",
  },
  {
    id: 12,
    name: "Product 12",
    tagline: "Dress",
    category: "male",
    price: 1200,
    image: P10,
    discount: 2,
    qty: 1,
    slug: "p12",
  },
  {
    id: 13,
    name: "Product 13",
    tagline: "Dress",
    category: "male",
    price: 1200,
    image: P11,
    discount: 2,
    qty: 1,
    slug: "p13",
  },
  {
    id: 14,
    name: "Product 14",
    tagline: "Dress",
    category: "kids",
    price: 1200,
    image: P11,
    discount: 2,
    qty: 1,
    slug: "p14",
  },
  {
    id: 15,
    name: "Product 15",
    tagline: "Dress",
    category: "female",
    price: 1200,
    image: P11,
    discount: 2,
    qty: 1,
    slug: "p15",
  },
  {
    id: 16,
    name: "Product 16",
    tagline: "Dress",
    category: "kids",
    price: 1200,
    image: P11,
    discount: 2,
    qty: 1,
    slug: "p16",
  },
  {
    id: 17,
    name: "Product 17",
    tagline: "Dress",
    category: "kids",
    price: 1200,
    image: P11,
    discount: 2,
    qty: 1,
    slug: "p17",
  },
  {
    id: 18,
    name: "Product 18",
    tagline: "Dress",
    category: "kids",
    price: 1200,
    image: P11,
    discount: 2,
    qty: 1,
    slug: "p18",
  },
];
